apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api-dev
  labels:
    run: poi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api-dev
  labels:
    app: poi-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrymoq4816.azurecr.io/tripinsights/poi:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminmOq4816"
        - name: SQL_PASSWORD
          value: "gY7c54Cr6"
        - name: SQL_SERVER
          value: "sqlservermoq4816.database.windows.net"
        - name: SQLDB
          value: "mydrivingDB"
