apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web-dev
  labels:
    run: tripviewer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tripviewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web-dev
  labels:
    app: tripviewer-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrymoq4816.azurecr.io/tripinsights/tripviewer:latest
        ports:
        - containerPort: 80
        env:
        - name: USER_API_ENDPOINT
          value: "http://userprofile"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips"
        volumeMounts:
        - name: flex
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: flex
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                             # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"                   # [OPTIONAL] if not provided, will default to "false"
            usevmmanagedidentity: "false"             # [OPTIONAL new in version >= v0.0.15] if not provided, will default to "false"
            vmmanagedidentityclientid: "clientid"     # [OPTIONAL new in version >= v0.0.15] use the client id to specify which user assigned managed identity to use, leave empty to use system assigned managed identity
            keyvaultname: "Teams12KeyVault"              # [REQUIRED] the name of the KeyVault
            keyvaultobjectnames: "SQLDB;SQLSERVER;SQLPASSWORD;SQLUSER"         # [REQUIRED] list of KeyVault object names (semi-colon separated)
            keyvaultobjectaliases: "SQLDB;SQL_SERVER;SQL_PASSWORD;SQL_USER"      # [OPTIONAL] list of KeyVault object aliases
            keyvaultobjecttypes: "secret;secret;secret;secret"              # [REQUIRED] list of KeyVault object types: secret, key, cert
            resourcegroup: "teamResources"        # [REQUIRED for version < v0.0.14] the resource group of the KeyVault
            subscriptionid: "e9ebdd32-b7fa-4f0a-a24f-84f0abd95900"                 # [REQUIRED for version < v0.0.14] the subscription ID of the KeyVault
            tenantid: "d6135023-56cd-4f8d-9e4b-bdf44a027d79"                    # [REQUIRED] the tenant ID of the KeyVault