apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-deployment
  labels:
    app: trips-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrymoq4816.azurecr.io/tripinsights/trips:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminmOq4816"
        - name: SQL_PASSWORD
          value: "gY7c54Cr6"
        - name: SQL_SERVER
          value: "sqlservermoq4816.database.windows.net"
        - name: SQLDB
          value: "mydrivingDB"