apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    run: user
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: registrymoq4816.azurecr.io/tripinsights/user-java:latest
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminmOq4816"
        - name: SQL_PASSWORD
          value: "gY7c54Cr6"
        - name: SQL_SERVER
          value: "sqlservermoq4816.database.windows.net"
        - name: SQLDB
          value: "mydrivingDB"
