apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web-dev
  name: web-dev-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
metadata:
  namespace: web-dev
  name: web-dev-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]